
services:

  # Default ports : see https://www.rabbitmq.com/networking.html#ports
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin" # don't use in prod, just demo
    ports:
      - "5672:5672"
      - "15692:15692"

  prometheus:
    image: prom/prometheus
    depends_on:
      - rabbitmq
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"

# https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose
volumes:
  prometheus-data: { }
